### ISSUE TITLE
issue found in kunal code

### ISSUE THREAD

**Issue by vivek84505** [hema1007/hemla_git_pr#8]
error found in compression.

![screenshot_2019-02-07 gzip compression live trends wordpress](https://user-images.githubusercontent.com/24931572/52407746-1ccd0e00-2af7-11e9-9a9f-fab6d945e39b.png)

**Comment by skunal2222** [comment]
nice screenshot

**Comment by vivek84505** [comment]
i am closing this issue.

**Comment by vivek84505** [comment]
i am closing this issue.

**Comment by skunal2222** [comment]
dfsg
